### ISSUE TITLE
JavaScript 库 + UI插件推荐 + 周边技术 — sunseekers

### ISSUE THREAD

**Issue by sunseekers** [sunseekers/sunseekers.github.io#1]
https://sunseekers.github.io/2019/07/05/web/ 

 日常工作用的 js 库，UI 插件痛点是：只有7秒钟的记忆，知道很多好用的库或者 UI ，但是每一次都说不出名字，都要各种查找，呼唤记忆。大量时间被浪费，这篇文章用做记录，方便我下次快速查找到，会陆续更新，有问题或者有好的推荐的朋友可以提pr，或者私聊我，我加上去。相信我个人的力量是有限的，我所列出基本都是公司项目中用过，或者朋友推荐。入职前端到目前一直使用的都是 vue ，所推荐有关 UI ，基本默认是  vue，在我的熟悉范围推荐。排名不分前后，瞎排，有可能不分文案写错了，欢迎指正部分内容具有时效性，所有内容仅供参考，如有侵权联系我进行删除

**Comment by sunseekers** [comment]
我是第一个留言的，哈哈，开心

**Comment by bran-nie** [comment]
火钳刘明

**Comment by Jancd** [comment]
刘明是谁
