### ISSUE TITLE
欢迎来到我的世界 — sunseekers

### ISSUE THREAD

**Issue by sunseekers** [sunseekers/sunseekers.github.io#2]
https://sunseekers.github.io/2019/07/04/hello-world/ 

 开启我的博客之旅为什么我要写博客距离上一次搭建博客是三年前了，但是三年前搭了一个框架，就没有下文了，那时候没啥可写的，就放弃了。现在觉得有些东西应该被记录，不能被遗忘，虽然有记事本，备忘录，有道笔记，他们都留下了我的痕迹，有些杂乱不成文，每次找起来都很不方便。所以博客他就诞生了，博客主要记录工作，微信公众号主要记录生活。

**Comment by qiutian00** [comment]
牛皮了 😄😄
