### ISSUE TITLE
vue 系列小实例 — sunseekers

### ISSUE THREAD

**Issue by sunseekers** [sunseekers/sunseekers.github.io#5]
https://sunseekers.github.io/2019/07/04/vue-practice/ 

 vue 动手系列搬运工，搬运可以动手尝试 vue 系列小实例。部分内容具有时效性，所有内容仅供参考，如有侵权联系我进行删除

**Comment by luoypwork** [comment]
加个好友 像大佬学习

**Comment by sunseekers** [comment]
> ```
>      加个好友 像大佬学习  
> ```

1390639401
