### ISSUE TITLE
嗨嗨嗨，主页无法留言了

### ISSUE THREAD

**Issue by gm0515** [sunseekers/sunseekers.github.io#54]
https://sunseekers.github.io/about/  这里git账号无法登录了

**Comment by bran-nie** [comment]
博主需要改一下gitalk的back_url，位于 Settings / Developer settings / OAuth Apps/

**Comment by sunseekers** [comment]
> https://sunseekers.github.io/about/ 这里git账号无法登录了

现在可以留言了，这个有段时间没有看了，后续慢慢优化一下

**Comment by sunseekers** [comment]
> 博主需要改一下gitalk的back_url，位于 Settings / Developer settings / OAuth Apps/

感谢，指导
